"""
CNSC Anisotropic f_NL Template — Development Artifact
=====================================================
Produces a quantitative reference for the null-geometry-only bispectrum
contribution f_NL^(2)(k) · P_2(mu), distinct from any scalar reskin.

Output: PNG + CSV + *_desc.md triple at outputs/figures/anisotropic_fNL_template.*

Caveat (also stated in docs/CNSC_Null_Geometry_Unique_Signature.md §7):
the prefactor below is a parametric estimate, not the result of a second-order
gauge-invariant perturbation calculation in the CNSC action.  It captures the
SHAPE (quadrupolar angular dependence with the DBI-saturation k-envelope) but
the overall amplitude requires the unfinished derivation.
"""
from __future__ import annotations
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent.parent
FIG_DIR = ROOT / "outputs" / "figures"
FIG_DIR.mkdir(parents=True, exist_ok=True)

# Same baseline params as verify_cnsc_predictions.py
M_GUT      = 1.0e16
LAMBDA_C   = 1.0e20
PHI_0      = 1.0e-5
H_STAR     = 1.0e-10
BETA_ALPHA = 0.01

def k_star() -> float:
    return (M_GUT**4 * H_STAR**2 / (LAMBDA_C * PHI_0**2)) ** 0.25

def fNL_iso(k) -> np.ndarray:
    """Isotropic part (DBI saturation, identical to scalar reskin)."""
    ks = k_star()
    gamma2 = 1.0 + (np.asarray(k) / ks)**4
    return (35.0 / 108.0) * (gamma2 - 1.0)

def fNL_aniso_envelope(k) -> np.ndarray:
    """
    Quadrupolar amplitude f_NL^(2)(k).
    Parametric: (beta/alpha) * (k/k*)^2 / (1 + (k/k*)^4) * f_NL^(0)(k).
    Peaks near the saturation scale k_* (causality-bounded).
    """
    ks = k_star()
    r = np.asarray(k) / ks
    envelope = r**2 / (1.0 + r**4)
    return BETA_ALPHA * envelope * fNL_iso(k)

def P2(mu: np.ndarray) -> np.ndarray:
    return 0.5 * (3.0 * mu**2 - 1.0)

# --- compute -----------------------------------------------------------------
k_grid = np.logspace(-2, 12, 600)
ks = k_star()
fNL_iso_grid = fNL_iso(k_grid)
fNL_aniso_grid = fNL_aniso_envelope(k_grid)

# angular slice at three benchmark scales
mu = np.linspace(-1.0, 1.0, 201)
bench_k = [1e2, ks, 1e10]
bench_curves = []
for kb in bench_k:
    f0 = float(fNL_iso(kb))
    f2 = float(fNL_aniso_envelope(kb))
    bench_curves.append((kb, f0, f2, f0 + f2 * P2(mu)))

# --- figure ------------------------------------------------------------------
fig, axes = plt.subplots(1, 2, figsize=(13, 5))
ax0, ax1 = axes

ax0.loglog(k_grid, np.abs(fNL_iso_grid),  color="tab:blue",   lw=2.0,
           label=r"$|f_{NL}^{(0)}(k)|$  (isotropic, scalar-reproducible)")
ax0.loglog(k_grid, np.abs(fNL_aniso_grid), color="tab:orange", lw=2.0,
           label=r"$|f_{NL}^{(2)}(k)|$  (quadrupolar, null-geometry only)")
ax0.axvline(ks, ls=":", color="black", alpha=0.7, label=fr"$k_*$ = {ks:.2e}")
ax0.set_xlabel(r"Wavenumber $k$  [Mpc$^{-1}$]")
ax0.set_ylabel(r"$|f_{NL}|$  amplitude")
ax0.set_title(r"(a) Isotropic vs quadrupolar $f_{NL}$ amplitudes")
ax0.grid(True, which="both", alpha=0.3)
ax0.legend(loc="upper left", bbox_to_anchor=(1.01, 1.0))

styles = ["-", "--", "-."]
for (kb, f0, f2, curve), st in zip(bench_curves, styles):
    ax1.plot(mu, curve, st, lw=2.0,
             label=fr"$k = {kb:.1e}$,  $f^{{(0)}}={f0:.2e}$,  $f^{{(2)}}={f2:.2e}$")
ax1.axhline(0.0, color="black", lw=0.6)
ax1.set_xlabel(r"$\mu = \hat k\cdot\hat\ell$")
ax1.set_ylabel(r"$f_{NL}(k,\mu)$")
ax1.set_title(r"(b) Angular template at three benchmark $k$")
ax1.set_xlim(-1.0, 1.0)
ax1.grid(True, alpha=0.3)
ax1.legend(loc="upper left", bbox_to_anchor=(1.01, 1.0), fontsize=9)

fig.suptitle(
    "CNSC null-geometry signature: quadrupolar $f_{NL}^{(2)}$ on top of the isotropic spectrum",
    fontsize=13)
fig.tight_layout()
fig_path = FIG_DIR / "anisotropic_fNL_template.png"
fig.savefig(fig_path, dpi=160, bbox_inches="tight")
plt.close(fig)

# --- CSV ---------------------------------------------------------------------
csv_grid = np.column_stack([k_grid, fNL_iso_grid, fNL_aniso_grid])
np.savetxt(FIG_DIR / "anisotropic_fNL_template.csv",
           csv_grid, delimiter=",",
           header="k_Mpc_inv,fNL_iso,fNL_aniso_envelope", comments="")

# --- desc --------------------------------------------------------------------
desc = f"""# Figure: anisotropic_fNL_template

## Purpose
Provide a quantitative reference template for the null-geometry-only bispectrum
contribution.  The isotropic part f_NL^(0)(k) coincides with any scalar reskin
of CNSC; the quadrupolar part f_NL^(2)(k) · P_2(mu) is the unique signature of
the shear invariant sigma_munu sigma^munu in the CNSC action.

## Data Source
- File: anisotropic_fNL_template.csv
- Generated by: outputs/verification/anisotropic_fNL_template.py
- Date: 2026-05-13

## Axes
- Panel (a) X: k (Mpc^-1), range 1e-2 to 1e12, log
- Panel (a) Y: |f_NL| amplitude (dimensionless), log
- Panel (b) X: mu = cos(theta) between k and l_hat, range -1 to 1
- Panel (b) Y: f_NL(k, mu) (dimensionless)

## Key Observations
- k_* = {ks:.3e}  (DBI saturation scale)
- Quadrupole envelope peaks near k = k_*; suppressed at both k << k_* and k >> k_*
- At k = k_*: |f_NL^(2)/f_NL^(0)| ~ (beta/alpha)/2 ~ 5e-3
- Angular slice flips sign across mu = +/- 1/sqrt(3) (zeros of P_2)
- A measurement of P_2-shaped anisotropy in the primordial bispectrum at any
  scale, with relative amplitude consistent with the envelope, supports CNSC's
  null-geometry sector.  Vanishing anisotropy with measured r ~ 0 reduces CNSC
  to its scalar projection.

## Reproduction
python outputs/verification/anisotropic_fNL_template.py
"""
(FIG_DIR / "anisotropic_fNL_template_desc.md").write_text(desc, encoding="utf-8")

print(f"k_*                      = {ks:.3e}")
print(f"f_NL^(0)(k=k_*)          = {float(fNL_iso(ks)):.3e}")
print(f"f_NL^(2)(k=k_*)          = {float(fNL_aniso_envelope(ks)):.3e}")
print(f"f_NL^(2)/f_NL^(0) at k_* = {float(fNL_aniso_envelope(ks))/float(fNL_iso(ks)):.3e}")
print(f"saved: {fig_path}")
